#!/bin/sh
[ $# -eq 0 ] || exit
cd "$(dirname "$0")"


## Config
export FONTDIR="$HOME/.fonts"


## Dependencies
[ -f "$FONTDIR" ] || mkdir "$FONTDIR"
command -v jq >/dev/null || {
  echo >&2 "jq: command not found"
  echo >&2 "Please install jq"
  return 127
}


case $1 in
  check)
    for module in modules/*; do
      sh $module check || echo "$(basename $(dirname $module)) needs updating"
    done
    exit;;

  update)
    for module in modules/*; do
      sh $module update
    done
    exit;;

  install|uninstall)
    [ -f "modules/$2" ] || {
      echo Font not recognized >&2
      exit 1
    }
    sh "modules/$2" $1
    exit;;

  install-all|uninstall-all)
    for module in modules/*; do
      sh $module ${1#-all}
    done
    exit;;

  *)
    echo Invalid command >&2
    exit 1;;
esac

# vim: et sw=2 sts=2 ts=2 ft=sh
