#!/bin/sh
[ $# -eq 0 ] && exit
cd "$(dirname "$0")"


## Config
export BASEDIR="$HOME/.fonts"


## Dependencies
[ -d "$BASEDIR" ] || mkdir "$BASEDIR"
command -v jq >/dev/null || {
  echo >&2 "jq: command not found"
  echo >&2 "Please install jq"
  return 127
}


case $1 in
  list)
    for module in modules/*; do
      echo "${module#modules/}"
    done
    exit;;

  check)
    ALL_GOOD=1
    for module in modules/*; do
      sh $module check >/dev/null || {
        case $? in
          (2) echo "${module#modules/} not installed";;
          (1) echo "${module#modules/} needs updating";;
        esac
        ALL_GOOD=0
      }
    done
    [ $ALL_GOOD = 1 ] && echo "All modules up-to-date"
    exit;;

  update)
    for module in modules/*; do
      sh $module update
    done
    exit;;

  install|uninstall)
    [ -f "modules/$2" ] || {
      echo Font not recognized >&2
      exit 1
    }
    sh "modules/$2" $1
    exit;;

  install-all|uninstall-all)
    for module in modules/*; do
      sh $module ${1#-all}
    done
    exit;;

  *)
    echo Invalid command >&2
    exit 1;;
esac

# vim: et sw=2 sts=2 ts=2 ft=sh
